"""Type stubs of the native extension (``crates/py/src/lib.rs``)."""

from collections.abc import Sequence
from os import PathLike
from typing import Any

import numpy as np
import numpy.typing as npt

STATE_DIM: int
#: ``(name, length)`` of the state row fields in order.
STATE_FIELDS: list[tuple[str, int]]
#: ``(name, bit)`` of the event bits.
EVENTS: list[tuple[str, int]]
TERMINAL_EVENTS: int

def native_version() -> str: ...
def normalize_scenario(text: str, toml: bool = False) -> str: ...
def default_scenario() -> str: ...
def vehicle_presets() -> list[str]: ...
def trailer_presets() -> list[str]: ...

class BatchSim:
    """``num_envs`` worlds of one scenario (JSON), stepped in parallel on ``num_threads``
    threads (0: one per logical CPU). Output arrays are overwritten in place."""

    def __init__(self, scenario: str, num_envs: int, seed: int = 0, num_threads: int = 0) -> None: ...
    def step(self, actions: npt.ArrayLike | Sequence[npt.ArrayLike]) -> None: ...
    def reset(
        self, mask: npt.NDArray[np.bool_] | Sequence[bool] | None = None, seeds: npt.ArrayLike | None = None
    ) -> None: ...
    def disable(self, group: int | str, mask: npt.NDArray[np.bool_]) -> None: ...
    def obs(self, group: int | str = 0) -> npt.NDArray[np.float32]: ...
    def state(self, group: int | str = 0) -> npt.NDArray[np.float64]: ...
    def events(self, group: int | str = 0) -> npt.NDArray[np.uint32]: ...
    @property
    def num_envs(self) -> int: ...
    @property
    def num_threads(self) -> int: ...
    @property
    def num_groups(self) -> int: ...
    @property
    def group_names(self) -> list[str]: ...
    @property
    def dt(self) -> float: ...
    @property
    def policy_dt(self) -> float: ...
    @property
    def decimation(self) -> int: ...
    @property
    def scenario_json(self) -> str: ...
    @property
    def map_hashes(self) -> list[str]: ...
    def group_info(self, group: int | str = 0) -> dict[str, Any]: ...
    def time(self, env: int) -> float: ...
    def map_index(self, env: int) -> int: ...
    def state_hash(self, env: int) -> bytes: ...
    def attach_recorder(
        self, env: int, path: str | PathLike[str], state_hz: int = 50, lidar: bool = False
    ) -> None: ...
    def detach_recorder(self, env: int) -> bool: ...
    def close(self) -> None: ...
